[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/simple-health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
FLASK_ENV = "production"
DISABLE_SELENIUM = "true"
PYTHONUNBUFFERED = "1"
WEB_CONCURRENCY = "1"
SESSION_COOKIE_DOMAIN = ".rallytennaqua.com"
PGCONNECT_TIMEOUT = "60"
PGPOOL_MIN_CONNECTIONS = "1"
PGPOOL_MAX_CONNECTIONS = "20"
GUNICORN_CMD_ARGS = "--bind=0.0.0.0:$PORT --workers=1 --timeout=120"
SKIP_DB_HEALTH_CHECK = "true" 