"""sync schema changes

Revision ID: 22cdc4d8bba3
Revises: c024866d32d0
Create Date: 2025-05-20 15:54:38.420328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cdc4d8bba3'
down_revision: Union[str, None] = 'c024866d32d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('idx_player_availability', table_name='player_availability')
    op.drop_constraint('player_availability_player_name_match_date_series_id_key', 'player_availability', type_='unique')
    op.alter_column('series', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_activity_logs', 'user_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_activity_logs', 'activity_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_activity_logs', 'page',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user_activity_logs', 'ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index('idx_user_activity_logs_user_email', table_name='user_activity_logs')
    op.alter_column('user_instructions', 'user_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_instructions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_user_instructions_email', table_name='user_instructions')
    op.drop_column('user_instructions', 'series_name')
    op.drop_column('user_instructions', 'team_name')
    op.drop_column('user_instructions', 'series_id')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'club_automation_password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_user_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'club_automation_password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'is_admin')
    op.add_column('user_instructions', sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_instructions', sa.Column('team_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_instructions', sa.Column('series_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_user_instructions_email', 'user_instructions', ['user_email'], unique=False)
    op.alter_column('user_instructions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('user_instructions', 'user_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_user_activity_logs_user_email', 'user_activity_logs', ['user_email', 'timestamp'], unique=False)
    op.alter_column('user_activity_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_activity_logs', 'page',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_activity_logs', 'activity_type',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_activity_logs', 'user_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('series', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint('player_availability_player_name_match_date_series_id_key', 'player_availability', ['player_name', 'match_date', 'series_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_player_availability', 'player_availability', ['player_name', 'match_date', 'series_id'], unique=False)
    op.alter_column('clubs', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
